dataset_prefix: example
result_dir: results
n_replicates: 10
threads: 2
seed: 42
plot_results: True
kmeans_k: 2
smartpca_optional_settings:
  numoutlieriter: 0

smartpca: /Users/julia/micromamba/envs/pca_micromamba/bin/smartpca
