dataset_prefix: example_sliding_window
n_components: 2
result_dir: results_sliding_window
analysis_mode: sliding_window
n_replicates: 10
threads: 2
seed: 42
plot_results: True
kmeans_k: 2
smartpca: /Users/julia/micromamba/envs/pca_micromamba/bin/smartpca
smartpca_optional_settings:
  numoutlieriter: 0
